version: "3.3"
services:
  orbeon:
    container_name: orbeon
    image: tiredofit/orbeon:latest
    ports:
      - "8081:8020"
    volumes:
      - "..:/usr/local/projects/numishare"
      - "..:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/apps/numishare"
      - "./exist-config.xml:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/apps/numishare/exist-config.xml"
      - "./server.xml:/usr/local/tomcat/conf/server.xml" 
      - "./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
      - "./web.xml:/usr/local/tomcat/webapps/orbeon/WEB-INF/web.xml"
      - "./properties-local.xml:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/config/properties-local.xml"
  solr:
    container_name: solr
    image: solr:8.6.2
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
      - "../solr-home/1.6:/var/solr/data/numishare"
    command:
      - solr-precreate
      - numishare-published

  exist:
    image: existdb/existdb:latest
    container_name: exist
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - type: volume
        source: data
        target: /exist/webapp/WEB-INF/data
      - type: volume
        source: config
        target: /exist/config

volumes:
  data:
    driver: local
  config:
    driver: local
